[project]
name = "research-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=1.4.0",
    "langchain-exa>=1.1.0",
    "langchain-openai>=1.2.2",
    "langgraph>=1.2.1",
    "langgraph-checkpoint-sqlite>=2.0.1",
    "langsmith>=0.1.0",
    "pydantic>=2.0",
    "python-dotenv>=1.0",
]
